exports.UITextMap = {
    file: "文件",
    save: "保存",
    otherOperation: "其他操作",
    view: "视图",
    tools: "工具",
    run: "运行",
    search: "搜索",
    logout: "注销",
    gettingFiles: "文件获取中……",
    task: "任务",
    tasks: "任务列表",
    details: "详细信息",
    stepIntoNext: "进入下一步",
    taskBackground: "任务背景",
    gettingTaskBackground: "正在获取任务背景……",
    taskGuide: "任务引导",
    gettingTaskGuide: "正在获取任务引导",
    requestCoordination: "协作",
    chatting: "聊天",
    terminal: "终端",
    stop: "停止",
    restart: "重启",
    courseGroup: "课程群",
    tutorials: "导师",
    member: "成员",
    memberList: "成员列表",
    send: "发送",
    help: "求助",
    addCollaboration: "添加协作",
    askTutorialForHelp: "求助导师",
    finish: "完成",
    follower: '输入小伙伴用户名',
    cooperateWithTask: "协作该任务",
    hideOrShow: "点击隐藏/显示",
    expandMemberList: "点击展开成员列表",
    clickHide: "点击隐藏",
    clear: "清空",
    login: "登录",
    userName: "用户名",
    password: "密码",
    chatRoom: "聊天室",
    hello: "你好",
    onlineUsers: "在线用户",
    pageNotFoundTip: "抱歉，找不到您要访问的页面...",
    errorCode: "错误代码",
    reminder: "温馨提示:",
    checkUrl: "1.请检查您访问的网址是否正确",
    otherCases: "2.当您点击某个链接时，它可能已经过期；系统或该页面正在维护中",
    returnHomePage: "返回首页",
    studentLearningCourse: "学生当前学习课程：",
    studentLearningCourseTime: "学生本次学习时长：",
    studentLearningCourseStatus: "学生当前学习进度：",
    studentUnfinishedCourse: "学生未完成的课程：",
    studentFinishedCourse: "学生已完成的课程：",
    course: "课程",
    user: "用户",
    operation: "操作",
    displayMonitorCourse: "课程监控显示排序",
    studentsSortByOnline: "按当前在线人数排序",
    studentsSortByHistoryLearning: "按历史学习人数排序",
    studentsSortByUnfinishedCourse: "按未完成该课程人数排序",
    studentsSortByFinishedCourse: "按已完成该课程人数排序",
    studentsSortByHistoryLearningM: "按历史学习人次排序",
    studentsSortByUnfinishedCourseM: "按未完成该课程人次排序",
    studentsSortByFinishedCourseM: "按已完成该课程人次排序",
    firstLevelMenu: "一级菜单",
    returnCurrentChatWindowByClick: "点击返回当前聊天窗口",
    openOrCloseCurrentWindow: "打开或关闭当前聊天窗口",
    viewDetails: "查看详细信息",
    startCooperativeOperation: "开始协同操作",
    runningInfo:"运行信息",
    unsuccessInfo:"该项目没有默认启动文件或者您还未打开想要运行的文件！",
    runningURL:"项目运行在:",
    illustrateURL:"演示地址",
    visit:"，快去访问吧！",
    alreadyRunning:"项目已经在：",
    alreadyRunningAndvisit:"运行了，快去访问吧！",
    stopProjectInfo:"停止运行信息：",
    restartProjectInfo:"重启项目信息：",
    restartSuccessINfo:"项目重启成功！运行在新的",
    openFileFailedInfo:"服务器出了一点点故障，刷新界面或者稍后再打开文件！",
    warmWarning:"你学得太快了吧！= =",
    iamEmoji:"我是一个Emoji",
    userNameIsNull:"还未输入用户名~！",
    readAndWrite:"读写",
    readOnly:"只读",
    systemInfo:"系统消息：",
    Offline:"下线了",
    online:"上线了",
    donotClick:"点自己干嘛!",
    chatContent:"聊天发送消息内容：",
    noRelevantFile:"没有相关文件",
    inviteSuccess:"邀请成功!",
    hasInviteSuccess:"您已经邀请过该用户!",
    fileTreeIsNull:"文件树为空!",
    finishedCourseInfo:"您已学完该课程！快去看看其他课程吧~",
    finishedCourseSuccess:"恭喜您学完此课程!",
    hasNoAccessToTheUsersTask:"您无权查看该用户学过的任务内容!",
    prompt:"提示：",
    currentTask:"当前任务：",
    connectToServerFailed:"系统，连接服务器失败",
    hasNoCourseIDAndCheck:"查询不到此课程，请检查您的课程ID是否正确！",
    noInputAndEnterDefault:"您还未输入课程ID，点击 OK 将进入默认课程演示！",
    couldnotFindCourseAndcheck:"查询不到此课程，请检查您的课程ID是否正确！",
    hasNoAccessToVisitTaskAndCheck:"您无权访问该学习过程，点击确定将为您引导到您上一次的学习过程或者重新分配一次过程！",
    serverHasProblemAndRefresh:"服务器出了一点点故障，刷新界面或者稍后再打开文件！",
    saveInfo:"保存信息：",
    cannotSaveThisFile:"此文件无法保存!",
    message:"消息",
    English: "English",
    Chinese: "中文",
    language: "语言",
    historyLearningCounts: "历史学习总人数/人次",
    unFinishedCourseCounts: "未完成该课程人数/人次",
    finishedCourseCounts: "已完成该课程人数/人次",
    onlineCounts: "当前在线人数",
    toDragAroundStretchingTheChatWindow : "向左右拖动拉伸聊天窗口",
    thisIsACourseDiscussionGroups : "这是一个课程讨论组",
    startCommunicationConnection : "建立通讯连接",
    descendingSort : "降序排序",
    ascendingSort :  "升序排序",
    sendMessageShortcuts : "消息发送快捷键",
    PressEnterToSendMessages : "按Enter键发送消息",
    PressCtrlAndEnterToSendMessages : "按Ctrl键+Enter键发送消息",
    loading : "加载中"
};
var UITextMap = exports.UITextMap;
